apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::144316422473:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-3pUjxghRTBz8
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::144316422473:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2024-05-07T08:53:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1488"
  uid: 761a9946-edce-4704-b3f3-f67732227e1e
